import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "../styles/globals.css";


const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${quicksand.variable} antialiased`}
    >
      <head>
        <meta name="view-transition" content="same-origin" />
      </head>
      <body className={`transition-colors duration-300 ${quicksand.className}`}>
        {children}
      </body>
    </html>
  );
}
