import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Aldayanday",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="antialiased dark" suppressHydrationWarning>
      <head>
        <meta name="view-transition" content="same-origin" />
      </head>
      <body className="transition-colors duration-300">{children}</body>
    </html>
  );
}
